<a href="https://colab.research.google.com/github/HirunaD/TensorFlow/blob/main/2_TensorVsNumpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Without GPU Support**

In [1]:
import numpy as np
import tensorflow as tf

In [2]:
import time

In [4]:
tf.test.gpu_device_name()

''

In [5]:
shape = 5000

In [8]:
np_array = np.random.uniform(size=[shape,shape])

In [9]:
np_array

array([[0.56870713, 0.40207072, 0.51590613, ..., 0.42191746, 0.72701452,
        0.47138232],
       [0.72166589, 0.28888199, 0.37759369, ..., 0.37583246, 0.79482457,
        0.93489675],
       [0.72736551, 0.29243285, 0.24826258, ..., 0.90412364, 0.7229219 ,
        0.25975177],
       ...,
       [0.77378104, 0.933435  , 0.68132085, ..., 0.34946524, 0.52950108,
        0.17078006],
       [0.34250861, 0.86355658, 0.87865366, ..., 0.25305418, 0.76425001,
        0.74398105],
       [0.90423268, 0.6848617 , 0.91440624, ..., 0.79621545, 0.96689646,
        0.95528285]])

In [10]:
start = time.time()

for i in range(10):
  np.matmul(np_array, np_array)

end = time.time()

time_period = end - start

print(f'{time_period} seconds')

87.03366160392761 seconds


In [12]:
tf_array = tf.random.uniform([shape,shape])
tf_array

<tf.Tensor: shape=(5000, 5000), dtype=float32, numpy=
array([[0.83157516, 0.08159602, 0.6825113 , ..., 0.41745508, 0.8743297 ,
        0.13771176],
       [0.06858444, 0.13870728, 0.62946546, ..., 0.70939183, 0.6969167 ,
        0.31077933],
       [0.96793556, 0.00159299, 0.5033606 , ..., 0.9322399 , 0.87113607,
        0.12798715],
       ...,
       [0.7478211 , 0.47004175, 0.08365309, ..., 0.56441665, 0.50319314,
        0.8957844 ],
       [0.23546767, 0.02326941, 0.42137253, ..., 0.97182107, 0.16614711,
        0.44496143],
       [0.8256724 , 0.7506033 , 0.84517884, ..., 0.78279114, 0.28267467,
        0.7969364 ]], dtype=float32)>

In [14]:
start = time.time()

for i in range(10):
  tf.matmul(tf_array, tf_array)

end = time.time()

time_period = end - start

print(f'{time_period} seconds')

47.94349694252014 seconds


**With GPU Support**

In [2]:
import numpy as np
import tensorflow as tf

In [3]:
import time

In [4]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [5]:
shape = 5000

In [6]:
np_array = np.random.uniform(size=[shape,shape])

In [7]:
np_array

array([[0.22375831, 0.93081052, 0.60896554, ..., 0.00538009, 0.01430539,
        0.10950017],
       [0.50080725, 0.44355111, 0.12201748, ..., 0.71034794, 0.78176323,
        0.87535075],
       [0.82030667, 0.50168502, 0.6177463 , ..., 0.65539555, 0.88322201,
        0.02901115],
       ...,
       [0.93025046, 0.39004778, 0.55664203, ..., 0.60180701, 0.18113166,
        0.49954552],
       [0.07783279, 0.33261161, 0.11163907, ..., 0.10380432, 0.68326778,
        0.37729182],
       [0.75034975, 0.54469591, 0.62253824, ..., 0.28767933, 0.96379188,
        0.07174054]])

In [8]:
start = time.time()

for i in range(10):
  np.matmul(np_array, np_array)

end = time.time()

time_period = end - start

print(f'{time_period} seconds')

52.55172157287598 seconds


In [9]:
tf_array = tf.random.uniform([shape,shape])
tf_array

<tf.Tensor: shape=(5000, 5000), dtype=float32, numpy=
array([[0.1298989 , 0.35359645, 0.4687475 , ..., 0.17909634, 0.22600245,
        0.3272184 ],
       [0.29792488, 0.00837874, 0.07234728, ..., 0.0181911 , 0.522915  ,
        0.35743058],
       [0.4382236 , 0.31444252, 0.3496871 , ..., 0.4966327 , 0.4476825 ,
        0.91275156],
       ...,
       [0.32673037, 0.67161894, 0.99850583, ..., 0.7946067 , 0.07950604,
        0.04528654],
       [0.0360148 , 0.47662067, 0.3645537 , ..., 0.8368709 , 0.5043328 ,
        0.35687745],
       [0.04793501, 0.9422462 , 0.07349277, ..., 0.24522638, 0.0016613 ,
        0.6929629 ]], dtype=float32)>

In [10]:
start = time.time()

for i in range(10):
  tf.matmul(tf_array, tf_array)

end = time.time()

time_period = end - start

print(f'{time_period} seconds')

0.15250468254089355 seconds
